name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Npm Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Run Unit tests
        run:  echo "Todo tests."
